const appConstants = {
  // Login.
  LOGIN_IN_PROGRESS: "LOGIN_IN_PROGRESS",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGIN_FAILURE: "LOGIN_ERROR",
  ADD_USERNAME: "ADD_USERNAME",
  // Specializari update.
  GET_SPECIALIZATIONS_IN_PROGRESS: "GET_SPECIALIZATIONS_IN_PROGRESS",
  GET_SPECIALIZATIONS_SUCCESS: "GET_SPECIALIZATIONS_SUCCESS",
  GET_SPECIALIZATIONS_FAILURE: "GET_SPECIALIZATIONS_ERROR",
  SET_SPECIALIZATION: "SET_SPECIALIZATION",
  // Medici UPDATE.
  GET_DOCTORS_IN_PROGRESS: "GET_DOCTORS_IN_PROGRESS",
  GET_DOCTORS_SUCCESS: "GET_DOCTORS_SUCCESS",
  GET_DOCTORS_FAILURE: "GET_DOCTORS_ERROR",
  // Medic UPDATE.
  GET_DOCTORPROFILE_IN_PROGRESS: "GET_DOCTORPROFILE_IN_PROGRESS",
  GET_DOCTORPROFILE_SUCCESS: "GET_DOCTORPROFILE_SUCCESS",
  GET_DOCTORPROFILE_FAILURE: "GET_DOCTORPROFILE_ERROR",
  // RecenziiMedic UPDATE.
  GET_DOCREVIEW_IN_PROGRESS: "GET_DOCREVIEW_IN_PROGRESS",
  GET_DOCREVIEW_SUCCESS: "GET_DOCREVIEW_SUCCESS",
  GET_DOCREVIEW_FAILURE: "GET_DOCREVIEW_ERROR",
  // Servicii update.
  GET_SERVICES_IN_PROGRESS: "GET_SERVICES_IN_PROGRESS",
  GET_SERVICES_SUCCESS: "GET_SERVICES_SUCCESS",
  GET_SERVICES_FAILURE: "GET_SERVICES_ERROR",
  // Program UPDATE.
  GET_SCHEDULE_IN_PROGRESS: "GET_SCHEDULE_IN_PROGRESS",
  GET_SCHEDULE_SUCCESS: " GET_SCHEDULE_SUCCESS",
  GET_SCHEDULE_FAILURE: "GET_SCHEDULE_ERROR",
  // Cabinete UPDATE.
  GET_OFFICES_IN_PROGRESS: "GET_OFFICES_IN_PROGRESS",
  GET_OFFICES_SUCCESS: " GET_OFFICES_SUCCESS",
  GET_OFFICES_FAILURE: "GET_OFFICES_ERROR",
  // Programari UPDATE.
  GET_APPOINTMENTS_IN_PROGRESS: "GET_APPOINTMENTS_IN_PROGRESS",
  GET_APPOINTMENTS_SUCCESS: "GET_APPOINTMENTS_SUCCESS",
  GET_APPOINTMENTS_FAILURE: "GET_APPOINTMENTS_ERROR",
  // Cabinet UPDATE.
  GET_OFFICEPROFILE_IN_PROGRESS: " GET_OFFICEPROFILE_IN_PROGRESS",
  GET_OFFICEPROFILE_SUCCESS: "GET_OFFICEPROFILE_SUCCESS",
  GET_OFFICEPROFILE_FAILURE: "GET_OFFICEPROFILE_ERROR",
  // Set status.
  SET_STATUS: "SET_STATUS",
  // Set id medic.
  SET_ID_DOCTOR: "SET_ID_DOCTOR"
};

export default appConstants;
